baseURL = "https://mohitmonnappa.github.io/"
locale = "en-us"
title = "Mohit's Writeups"
paginate = 10

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    lineNos = false
    tabWidth = 2
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "CTF · web · pwn · crypto notes"
  github = "https://github.com/mohitmonnappa"
  author = "Mohit Monnappa T N"
